apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-dwarf
  labels:
    app: webserver-dwarf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver-dwarf
  template:
    metadata:
      labels:
        app: webserver-dwarf
    spec:
      containers:
      - name: red-dwarf
        image: smidra/yellow-dwarf
        ports:
        - containerPort: 80
      terminationGracePeriodSeconds: 4

---
apiVersion: v1
kind: Service
metadata:
  name: dwarf-svc
spec:
  selector:
    app: webserver-dwarf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
